[Actions] Adding a MacOS build workflow, fixing several MacOS specific compilation errors and warnings (#327)
* Adding a macOS build template

* Add a workflow file for macOS build

* Remove the architecture specification from the build command

* Disabling DeviceIdentification plugin due to no platform backend 

CMake Error at DeviceIdentification/CMakeLists.txt:116 (message):
  There is no platform backend for device identifier plugin

* Mark all Message method from Publishers as overrides

* Bring Attach and Detach from PluginHost::JSONRPC into the MessageControl class

* Try to enable the const copy constructor of MonitorObject to see if that's the root cause

* The operators have to be deleted, bring it back

* Removing the proper copy and assignemtn operators with const instead

* Remove one instance of operator= deletion

* Make sure to include the fno-gnu-unique flag only for GCC

* Slight formatting changes

* Adding a missing override

* Adding overrides and marking member variable as not used

[18/34] Building CXX object OpenCDMi/CMakeFiles/ThunderOCDM.dir/CENCParser.cpp.o
FAILED: OpenCDMi/CMakeFiles/ThunderOCDM.dir/CENCParser.cpp.o 
/Applications/Xcode_15.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DPROCESSCONTAINERS_ENABLED=1 -DTHUNDER_PLATFORM_PC_UNIX=1 -DThunderOCDM_EXPORTS -DWARNING_REPORTING_ENABLED -D_TRACE_LEVEL=0 -D__CORE_MESSAGING__ -D__CORE_NO_WCHAR_SUPPORT__ -D__CORE_WARNING_REPORTING__ -isystem /Users/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/Release/install/usr/include/Thunder -isystem /Users/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/Release/install/usr/include -isystem /Users/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/Release/install/usr/include/Thunder/processcontainers -Wall -Wextra -Wpedantic -Werror -O3 -DNDEBUG -std=gnu++11 -arch arm64 -isysroot /Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -MD -MT OpenCDMi/CMakeFiles/ThunderOCDM.dir/CENCParser.cpp.o -MF OpenCDMi/CMakeFiles/ThunderOCDM.dir/CENCParser.cpp.o.d -o OpenCDMi/CMakeFiles/ThunderOCDM.dir/CENCParser.cpp.o -c /Users/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/ThunderNanoServicesRDK/OpenCDMi/CENCParser.cpp
In file included from /Users/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/ThunderNanoServicesRDK/OpenCDMi/CENCParser.cpp:20:
In file included from /Users/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/ThunderNanoServicesRDK/OpenCDMi/CENCParser.h:25:
/Users/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/ThunderNanoServicesRDK/OpenCDMi/Protobuf.h:466:18: error: 'Type' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
        WireType Type() const {
                 ^
/Users/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/ThunderNanoServicesRDK/OpenCDMi/Protobuf.h:40:26: note: overridden virtual function is here
        virtual WireType Type() const = 0;
                         ^
1 error generated.
[19/34] Building CXX object Monitor/CMakeFiles/ThunderMonitor.dir/Monitor.cpp.o
[20/34] Building CXX object OpenCDMi/CMakeFiles/ThunderOCDM.dir/OCDM.cpp.o
[21/34] Building CXX object OpenCDMi/CMakeFiles/ThunderOCDM.dir/OCDMJsonRpc.cpp.o
[22/34] Building CXX object OpenCDMi/CMakeFiles/ThunderOCDM.dir/FrameworkRPC.cpp.o
FAILED: OpenCDMi/CMakeFiles/ThunderOCDM.dir/FrameworkRPC.cpp.o 
/Applications/Xcode_15.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DPROCESSCONTAINERS_ENABLED=1 -DTHUNDER_PLATFORM_PC_UNIX=1 -DThunderOCDM_EXPORTS -DWARNING_REPORTING_ENABLED -D_TRACE_LEVEL=0 -D__CORE_MESSAGING__ -D__CORE_NO_WCHAR_SUPPORT__ -D__CORE_WARNING_REPORTING__ -isystem /Users/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/Release/install/usr/include/Thunder -isystem /Users/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/Release/install/usr/include -isystem /Users/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/Release/install/usr/include/Thunder/processcontainers -Wall -Wextra -Wpedantic -Werror -O3 -DNDEBUG -std=gnu++11 -arch arm64 -isysroot /Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -MD -MT OpenCDMi/CMakeFiles/ThunderOCDM.dir/FrameworkRPC.cpp.o -MF OpenCDMi/CMakeFiles/ThunderOCDM.dir/FrameworkRPC.cpp.o.d -o OpenCDMi/CMakeFiles/ThunderOCDM.dir/FrameworkRPC.cpp.o -c /Users/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/ThunderNanoServicesRDK/OpenCDMi/FrameworkRPC.cpp
In file included from /Users/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/ThunderNanoServicesRDK/OpenCDMi/FrameworkRPC.cpp:25:
In file included from /Users/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/ThunderNanoServicesRDK/OpenCDMi/CENCParser.h:25:
/Users/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/ThunderNanoServicesRDK/OpenCDMi/Protobuf.h:466:18: error: 'Type' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
        WireType Type() const {
                 ^
/Users/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/ThunderNanoServicesRDK/OpenCDMi/Protobuf.h:40:26: note: overridden virtual function is here
        virtual WireType Type() const = 0;
                         ^
/Users/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/ThunderNanoServicesRDK/OpenCDMi/FrameworkRPC.cpp:953:35: error: 'GetSecureStopIds' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
            Exchange::OCDM_RESULT GetSecureStopIds(
                                  ^
/Users/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/Release/install/usr/include/Thunder/interfaces/IOCDM.h:229:25: note: overridden virtual function is here
    virtual OCDM_RESULT GetSecureStopIds(const string& keySystem,
                        ^
/Users/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/ThunderNanoServicesRDK/OpenCDMi/FrameworkRPC.cpp:980:35: error: 'CommitSecureStop' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
            Exchange::OCDM_RESULT CommitSecureStop(
                                  ^
/Users/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/Release/install/usr/include/Thunder/interfaces/IOCDM.h:240:25: note: overridden virtual function is here
    virtual OCDM_RESULT CommitSecureStop(const string& keySystem,
                        ^
/Users/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/ThunderNanoServicesRDK/OpenCDMi/FrameworkRPC.cpp:1421:26: error: 'Reset' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
        virtual uint32_t Reset()
                         ^
/Users/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/Release/install/usr/include/Thunder/interfaces/IContentDecryption.h:35:26: note: overridden virtual function is here
        virtual uint32_t Reset() = 0;
                         ^
/Users/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/ThunderNanoServicesRDK/OpenCDMi/FrameworkRPC.cpp:1425:39: error: 'Systems' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
        virtual RPC::IStringIterator* Systems() const
                                      ^
/Users/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/Release/install/usr/include/Thunder/interfaces/IContentDecryption.h:36:39: note: overridden virtual function is here
        virtual RPC::IStringIterator* Systems() const = 0;
                                      ^
/Users/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/ThunderNanoServicesRDK/OpenCDMi/FrameworkRPC.cpp:1429:39: error: 'Designators' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
        virtual RPC::IStringIterator* Designators(const string& keySystem) const
                                      ^
/Users/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/Release/install/usr/include/Thunder/interfaces/IContentDecryption.h:37:39: note: overridden virtual function is here
        virtual RPC::IStringIterator* Designators(const string& keySystem) const = 0;
                                      ^
/Users/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/ThunderNanoServicesRDK/OpenCDMi/FrameworkRPC.cpp:1435:39: error: 'Sessions' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
        virtual RPC::IStringIterator* Sessions(const string& keySystem) const
                                      ^
/Users/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/Release/install/usr/include/Thunder/interfaces/IContentDecryption.h:38:39: note: overridden virtual function is here
        virtual RPC::IStringIterator* Sessions(const string& keySystem) const = 0;
                                      ^
/Users/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/ThunderNanoServicesRDK/OpenCDMi/FrameworkRPC.cpp:378:48: error: private field '_mediaKeysExt' is not used [-Werror,-Wunused-private-field]
                    CDMi::IMediaKeySessionExt* _mediaKeysExt;
                                               ^
/Users/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/ThunderNanoServicesRDK/OpenCDMi/FrameworkRPC.cpp:379:30: error: private field '_sessionKey' is not used [-Werror,-Wunused-private-field]
                    uint8_t* _sessionKey;
                             ^
/Users/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/ThunderNanoServicesRDK/OpenCDMi/FrameworkRPC.cpp:380:30: error: private field '_sessionKeyLength' is not used [-Werror,-Wunused-private-field]
                    uint32_t _sessionKeyLength;
                             ^
/Users/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/ThunderNanoServicesRDK/OpenCDMi/FrameworkRPC.cpp:751:34: error: private field '_refCount' is not used [-Werror,-Wunused-private-field]
                mutable uint32_t _refCount;
                                 ^
11 errors generated.

* Mark the PerformanceMetrics methods as overrides of IPlugin

[28/34] Building CXX object PerformanceMetrics/CMakeFiles/ThunderPerformanceMetrics.dir/PerformanceMetrics.cpp.o
FAILED: PerformanceMetrics/CMakeFiles/ThunderPerformanceMetrics.dir/PerformanceMetrics.cpp.o 
/Applications/Xcode_15.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DPROCESSCONTAINERS_ENABLED=1 -DTHUNDER_PLATFORM_PC_UNIX=1 -DThunderPerformanceMetrics_EXPORTS -DWARNING_REPORTING_ENABLED -D_TRACE_LEVEL=0 -D__CORE_MESSAGING__ -D__CORE_NO_WCHAR_SUPPORT__ -D__CORE_WARNING_REPORTING__ -isystem /Users/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/Debug/install/usr/include/Thunder -isystem /Users/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/Debug/install/usr/include -isystem /Users/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/Debug/install/usr/include/Thunder/processcontainers -Wall -Wextra -Wpedantic -Werror -g -std=gnu++11 -arch arm64 -isysroot /Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -O0 -g -MD -MT PerformanceMetrics/CMakeFiles/ThunderPerformanceMetrics.dir/PerformanceMetrics.cpp.o -MF PerformanceMetrics/CMakeFiles/ThunderPerformanceMetrics.dir/PerformanceMetrics.cpp.o.d -o PerformanceMetrics/CMakeFiles/ThunderPerformanceMetrics.dir/PerformanceMetrics.cpp.o -c /Users/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/ThunderNanoServicesRDK/PerformanceMetrics/PerformanceMetrics.cpp
In file included from /Users/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/ThunderNanoServicesRDK/PerformanceMetrics/PerformanceMetrics.cpp:20:
/Users/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/ThunderNanoServicesRDK/PerformanceMetrics/PerformanceMetrics.h:667:30: error: 'Initialize' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
        virtual const string Initialize(PluginHost::IShell* service);
                             ^
/Users/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/Debug/install/usr/include/Thunder/plugins/IPlugin.h:81:30: note: overridden virtual function is here
        virtual const string Initialize(PluginHost::IShell* shell) = 0;
                             ^
In file included from /Users/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/ThunderNanoServicesRDK/PerformanceMetrics/PerformanceMetrics.cpp:20:
/Users/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/ThunderNanoServicesRDK/PerformanceMetrics/PerformanceMetrics.h:673:22: error: 'Deinitialize' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
        virtual void Deinitialize(PluginHost::IShell* service);
                     ^
/Users/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/Debug/install/usr/include/Thunder/plugins/IPlugin.h:90:22: note: overridden virtual function is here
        virtual void Deinitialize(PluginHost::IShell* shell) = 0;
                     ^
In file included from /Users/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/ThunderNanoServicesRDK/PerformanceMetrics/PerformanceMetrics.cpp:20:
/Users/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/ThunderNanoServicesRDK/PerformanceMetrics/PerformanceMetrics.h:677:24: error: 'Information' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
        virtual string Information() const;
                       ^
/Users/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/Debug/install/usr/include/Thunder/plugins/IPlugin.h:97:24: note: overridden virtual function is here
        virtual string Information() const = 0;
                       ^
3 errors generated.

* Mark Activated from TraceOutput as an override of a method from PerformanceMetrics

 /Users/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/ThunderNanoServicesRDK/PerformanceMetrics/TraceOutput.cpp:161:10: error: 'Activated' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
    void Activated() 
         ^
/Users/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/ThunderNanoServicesRDK/PerformanceMetrics/PerformanceMetrics.h:104:26: note: overridden virtual function is here
            virtual void Activated()  = 0;
                         ^

* Removing instantiation of LoggerFactory that occurs after specialization

/Users/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/ThunderNanoServicesRDK/PerformanceMetrics/TraceOutput.cpp:229:89: error: explicit instantiation of 'LoggerFactory<Thunder::Plugin::PerformanceMetrics::IBrowserMetricsLogger>' that occurs after an explicit specialization has no effect [-Werror,-Winstantiation-after-specialization]
template std::unique_ptr<PerformanceMetrics::IBrowserMetricsLogger> PerformanceMetrics::LoggerFactory<PerformanceMetrics::IBrowserMetricsLogger>();                
                                                                                        ^
/Users/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/ThunderNanoServicesRDK/PerformanceMetrics/TraceOutput.cpp:223:80: note: previous template specialization is here
std::unique_ptr<PerformanceMetrics::IBrowserMetricsLogger> PerformanceMetrics::LoggerFactory<PerformanceMetrics::IBrowserMetricsLogger>() {

* Add override to Activated in TraceOutput

[28/34] Building CXX object PerformanceMetrics/CMakeFiles/ThunderPerformanceMetrics.dir/TraceOutput.cpp.o
FAILED: PerformanceMetrics/CMakeFiles/ThunderPerformanceMetrics.dir/TraceOutput.cpp.o 
/Applications/Xcode_15.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DPROCESSCONTAINERS_ENABLED=1 -DTHUNDER_PLATFORM_PC_UNIX=1 -DThunderPerformanceMetrics_EXPORTS -DWARNING_REPORTING_ENABLED -D_TRACE_LEVEL=0 -D__CORE_MESSAGING__ -D__CORE_NO_WCHAR_SUPPORT__ -D__CORE_WARNING_REPORTING__ -isystem /Users/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/Release/install/usr/include/Thunder -isystem /Users/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/Release/install/usr/include -isystem /Users/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/Release/install/usr/include/Thunder/processcontainers -Wall -Wextra -Wpedantic -Werror -O3 -DNDEBUG -std=gnu++11 -arch arm64 -isysroot /Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -MD -MT PerformanceMetrics/CMakeFiles/ThunderPerformanceMetrics.dir/TraceOutput.cpp.o -MF PerformanceMetrics/CMakeFiles/ThunderPerformanceMetrics.dir/TraceOutput.cpp.o.d -o PerformanceMetrics/CMakeFiles/ThunderPerformanceMetrics.dir/TraceOutput.cpp.o -c /Users/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/ThunderNanoServicesRDK/PerformanceMetrics/TraceOutput.cpp
/Users/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/ThunderNanoServicesRDK/PerformanceMetrics/TraceOutput.cpp:161:10: error: 'Activated' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
    void Activated() 
         ^
/Users/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/ThunderNanoServicesRDK/PerformanceMetrics/PerformanceMetrics.h:104:26: note: overridden virtual function is here
            virtual void Activated()  = 0;
                         ^
1 error generated.

* Use the template from master and update the trigger conditions