Parentheses around assignment used as truth value
/home/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/ThunderNanoServicesRDK/PlayerInfo/GStreamer/PlatformImplementation.cpp:61:17: error: suggest parentheses around assignment used as truth value [-Werror=parentheses]
   61 |                 if (elements = std::move(GstUtils::GstRegistryGetElementForMediaType(decoderFactories.get(), std::move(mediaType)))) {
      |                 ^~
/home/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/ThunderNanoServicesRDK/PlayerInfo/GStreamer/PlatformImplementation.cpp:64:24: error: suggest parentheses around assignment used as truth value [-Werror=parentheses]
   64 |                 } else if (elements = std::move(GstUtils::GstRegistryGetElementForMediaType(parserFactories.get(), std::move(mediaType)))) {
      |                        ^~
/home/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/ThunderNanoServicesRDK/PlayerInfo/GStreamer/PlatformImplementation.cpp: In instantiation of ‘static bool Thunder::Plugin::PlayerInfoImplementation::GstUtils::GstRegistryCheckElementsForMediaTypes(C, CodecIteratorList&) [with C = std::map<const std::__cxx11::basic_string<char>, const Thunder::Exchange::IPlayerProperties::VideoCodec>; CodecIteratorList = std::__cxx11::list<Thunder::Exchange::IPlayerProperties::VideoCodec>]’:
/home/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/ThunderNanoServicesRDK/PlayerInfo/GStreamer/PlatformImplementation.cpp:188:60:   required from here
/home/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/ThunderNanoServicesRDK/PlayerInfo/GStreamer/PlatformImplementation.cpp:61:17: error: suggest parentheses around assignment used as truth value [-Werror=parentheses]
   61 |                 if (elements = std::move(GstUtils::GstRegistryGetElementForMediaType(decoderFactories.get(), std::move(mediaType)))) {
      |                 ^~
/home/runner/work/ThunderNanoServicesRDK/ThunderNanoServicesRDK/ThunderNanoServicesRDK/PlayerInfo/GStreamer/PlatformImplementation.cpp:64:24: error: suggest parentheses around assignment used as truth value [-Werror=parentheses]
   64 |                 } else if (elements = std::move(GstUtils::GstRegistryGetElementForMediaType(parserFactories.get(), std::move(mediaType)))) {
      |                        ^~